config/routes.rb
Rails.application.routes.draw do
  resources :wins
  resource :session
  resources :passwords, param: :token
  resource :registration, only: %i[new create]
  resource :user_profile, only: [ :edit, :update ], controller: "user_profile"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/win.rb
# == Schema Information
#
# Table name: wins
#
#  id               :integer          not null, primary key
#  title            :string
#  description      :text
#  impact           :text
#  achievement_date :date
#  private_notes    :text
#  user_id          :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_wins_on_user_id  (user_id)
#

class Win < ApplicationRecord
  belongs_to :user
end

app/controllers/wins_controller.rb
class WinsController < ApplicationController
  before_action :set_win, only: %i[ show edit update destroy ]
  before_action :require_authentication

  # GET /wins or /wins.json
  def index
    @new_win = Win.new
    @wins = Current.user.wins
  end

  # GET /wins/1 or /wins/1.json
  def show
  end

  # GET /wins/new
  def new
    @win = Win.new
  end

  # GET /wins/1/edit
  def edit
  end

  # POST /wins or /wins.json
  def create
    @win = Win.new(win_params)

    respond_to do |format|
      if @win.save
        format.html { redirect_to @win, notice: "Win was successfully created." }
        format.json { render :show, status: :created, location: @win }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @win.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wins/1 or /wins/1.json
  def update
    respond_to do |format|
      if @win.update(win_params)
        format.html { redirect_to @win, notice: "Win was successfully updated." }
        format.json { render :show, status: :ok, location: @win }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @win.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wins/1 or /wins/1.json
  def destroy
    @win.destroy!

    respond_to do |format|
      format.html { redirect_to wins_path, status: :see_other, notice: "Win was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_win
      @win = Win.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def win_params
      params.expect(win: [ :title, :description, :impact, :achievement_date, :private_notes, :user_id ])
    end
end

app/helpers/wins_helper.rb
module WinsHelper
end

app/views/wins/_form.html.erb
<%= form_with(model: win, 
    data: { 
      controller: "toggle-content",
      "show-more-hidden-class": "hidden"
    }, 
    class: "card bg-base-100 shadow-md mb-24 mt-16 max-w-xl mx-auto border border-base-300 rounded-sm p-6 space-y-4") do |form| %>
  <% if win.errors.any? %>
    <div role="alert" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <div>
        <h3 class="font-bold"><%= pluralize(win.errors.count, "error") %> prohibited this win from being saved:</h3>
        <div class="text-xs">
          <% win.errors.each do |error| %>
            <div><%= error.full_message %></div>
          <% end %>
        </div>
      </div>
    <% end %>

  <div class="flex gap-x-2">
    <div class="form-control w-full card">
      <%= form.text_field :title, placeholder: "Name your win!", class: "!outline-none input input-bordered w-full" %>
    </div>
    <div class="form-control ">
      <%= form.date_field :achievement_date, 
      class: "!outline-none input input-bordered w-full", 
      value: Date.today.to_s %>
    </div>
  </div>

  <div class="form-control w-full">
    <%= form.textarea :description, placeholder: "Provide notes of what you accomplished and the impact of your work.\nExample: 'Completed project B and have seen an increase in sales by 7% in a week' ", class: "!outline-none textarea textarea-bordered w-full" %>
  </div>

  <div 
    data-toggle-content-target="toggleContent" 
    class="hidden space-y-4"
  >
    <div class="form-control w-full">
      <%= form.label :impact, class: "label" %>
      <%= form.textarea :impact, class: "!outline-none textarea textarea-bordered w-full" %>
    </div>

    <div class="w-full">
      <%= form.label :private_notes, class: "label" %>
      <%= form.textarea :private_notes, class: "!outline-none textarea textarea-bordered w-full" %>
    </div>
  </div>

  <%= form.hidden_field :user_id, value: Current.user.id %>

<div class="join w-full">

    <button 
      type="button"
      data-toggle-content-target="toggleButton"
      data-action="click->toggle-content#toggle"
      data-toggle-content-on-param="Hide Details"
      data-toggle-content-off-param="Add Details"
      class="btn !m-0 join-item w-1/2"
    >
    Add Details
    </button>
    <%= form.submit "Save Win", class: "w-1/2 btn btn-primary join-item " %>

</div>

<% end %>

app/views/wins/_win.html.erb
<div id="<%= dom_id win %>">
 <div class="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -start-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
 <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500"><%= win.achievement_date %></time>
 <h3 class="text-lg font-semibold text-gray-900 dark:text-white"><%= win.title %></h3>
 <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400"><%=win.description %></p>
 <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400"><%=win.impact %></p>
 <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400"><%=win.private_notes %></p>
</div>

app/views/wins/edit.html.erb
<% content_for :title, "Editing win" %>

<h1>Editing win</h1>

<%= render "form", win: @win %>

<br>

<div>
  <%= link_to "Show this win", @win %> |
  <%= link_to "Back to wins", wins_path %>
</div>

app/views/wins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center text-2xl font-bold mb-6">Wins</h1>

<div class="bg-base-200 hidden p-4 max-w-xl italic text-base-content/70 mx-auto">
<p class="mb-2">
Documenting your wins is crucial to gathering the materials you'll need later to make a case for your next promotion (or even your next job).
</p>
<p>
Start by getting it all down here, big or small.
</p>
<button class="btn mt-2"> Got it!</button> 
</div>

<%= render "form", win: @new_win %>

<div id="wins" class="container mx-auto px-4 relative text-base-content">
  <div class="absolute left-1/2 top-0 bottom-0 w-0.5 bg-base-300"></div>
  
  <ol class="relative">                  
    <% @wins.each_with_index do |win, index| %>
      <li class="mb-10 relative text-base-content">
        <%= link_to win do %>
          <div class="<%= index.even? ? 'lg:pe-8 text-end' : 'lg:ps-8' %> relative">
            
          <div class="absolute left-1/2 top-1/2 bottom-1/2 h-3 w-3 -mt-1.5 -ml-[5px] rounded-lg bg-base-300"></div>
            
            <div class=" max-w-md inline-block text-start card rounded-sm bg-base-300 p-2 px-4">
              <time class="mb-1 text-sm font-normal leading-none"><%= win.achievement_date %></time>
              <h3 class="text-lg font-semibold"><%= win.title %></h3>
              
              <% if win.description.present? %>
                <p class="mb-4 text-base text-sm font-normal"><%= win.description %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ol>
</div>

<div class="text-center mt-6">
  <%= link_to "New win", new_win_path, class: "btn btn-primary" %>
</div>

app/views/wins/new.html.erb
<% content_for :title, "New win" %>

<h1>New win</h1>

<%= render "form", win: @win %>

<br>

<div>
  <%= link_to "Back to wins", wins_path %>
</div>

app/views/wins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @win %>

<div>
  <%= link_to "Edit this win", edit_win_path(@win) %> |
  <%= link_to "Back to wins", wins_path %>

  <%= button_to "Destroy this win", @win, method: :delete %>
</div>